name: Publish Package to npmjs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - name: Get the version
        id: package
        run: echo "version=$(node -p 'require("./packages/svg/config.json").version')" >> "$GITHUB_ENV"
      - run: git config --global user.email "meakle@qq.com" 
      - run: git config --global user.name "asen"

      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn build
      - run: yarn version --new-version ${{ env.version }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}